### PR TITLE
feat: set path for img src when only passes string

### PR DESCRIPTION
**Pull request by malavshah9**
Fulfills https://github.com/wyozi/react-pptx/issues/232

### CODE REVIEW

**Comment by malavshah9** [comment]
@wyozi Please review this in return of https://github.com/wyozi/react-pptx/issues/232

**Review by wyozi — CHANGES_REQUESTED** [review]
I think this is better done a bit differently:
1. `InternalImage` in normalizer should not have a `string`, but instead the normalizer should automatically wrap a string `src` into a `InternalImageSrc`. You could create something like `normalizeImageSrc` in the file for this purpose
2. Renderer would then not have to be changed at all since it would still accept the same old type of input

**Comment by wyozi** [comment]
Thanks for PR!

**Comment by malavshah9** [comment]
@wyozi  Updated!

**Comment by wyozi** [comment]
LGTM. Thanks!

**Pull request merged**
