### PR TITLE
Feat: <Table> header support

### PR DESCRIPTION
**Pull request by juanesquintero**
Enable `<Table/>` inner border preview 
Add header prop to `<Table/>`

### CODE REVIEW

**Comment by juanesquintero** [comment]
@wyozi Hey Joonas! Do you think is a good approach to insert a `header` prop or either way implement a full `<Table.Cell>` component?

**Comment by wyozi** [comment]
@juanesquintero if I understood correctly the goal of `header` prop would be making a cell that is as wide as the table. In that case I think a full-on `<Table.Cell>` would work more nicely here and be a bit more generic

**Comment by wyozi** [comment]
Looking at pptxgenjs' `TableCellProps` type, maybe `<Table.Cell>` could extend `<Text>` props too and add the extra props (including colspan). But you can experiment a bit and see what works

**Comment by juanesquintero** [comment]
@wyozi Agree with you,  with that approach it will be a must to inserted as a children component to Table or still send it as rows? 
Also it has to support both Text and Table.Cell to support Links and other or just Table.Cell

**Pull request closed without merging**
