### PR TITLE
#111 Adds Speaker Notes support

### PR DESCRIPTION
**Pull request by ksk385**
Hi,

This is my first contribution to this repo. Please let me know how I can test my work.

Thanks,
Karan

### CODE REVIEW

**Comment by wyozi** [comment]
@ksk385 testing is not quite optimal yet, but best way is to add speaker notes to index.spec.tsx, run `npm run test` and open the generated pptx file to see if it works properly

**Comment by wyozi** [comment]
Thanks for the PR! Looks pretty good. However, you'll still need to transfer the `notes` string to `InternalSlide` at https://github.com/wyozi/react-pptx/blob/master/src/normalizer.ts#L388

**Comment by ksk385** [comment]
Thanks for the advice @wyozi , I was able to test rendering using the unit test. Also did manual testing by building the demo and checking there. Was not able to figure out the JSON structure to grab notes from a Slide in the e2e test.

If you know specifically how to point out notes on a Slide for the assertion I am happy to add that in as well.

**Comment by wyozi** [comment]
No need to dig too deep into it. My approach with it has been just quickly seeing if there's anything testable there anyway :)

Thanks for the PR!

**Pull request merged**
